//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseTrackerApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBONLINETESTEntities : DbContext
    {
        public DBONLINETESTEntities()
            : base("name=DBONLINETESTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<tblAssignExam_ToAgent> tblAssignExam_ToAgent { get; set; }
        public virtual DbSet<tblQuestion> tblQuestions { get; set; }
        public virtual DbSet<tblQuestionType> tblQuestionTypes { get; set; }
        public virtual DbSet<tblQuiz> tblQuizs { get; set; }
        public virtual DbSet<tblResult> tblResults { get; set; }
        public virtual DbSet<tblSubject> tblSubjects { get; set; }
        public virtual DbSet<tblTestCategory> tblTestCategories { get; set; }
        public virtual DbSet<tblTestSetting> tblTestSettings { get; set; }
        public virtual DbSet<tblUserAnswer> tblUserAnswers { get; set; }
        public virtual DbSet<tblUserDetail> tblUserDetails { get; set; }
        public virtual DbSet<tblUserForm> tblUserForms { get; set; }
        public virtual DbSet<tblUserPermission> tblUserPermissions { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblAdminDetail> tblAdminDetails { get; set; }
        public virtual DbSet<tblCategoryMapping> tblCategoryMappings { get; set; }
        public virtual DbSet<tblSecretQuestion> tblSecretQuestions { get; set; }
        public virtual DbSet<tblUserRole> tblUserRoles { get; set; }
    
        public virtual int addQuestion(string questionType, string category, string question, string optionA, string optionB, string optionC, string optionD, string answer)
        {
            var questionTypeParameter = questionType != null ?
                new ObjectParameter("QuestionType", questionType) :
                new ObjectParameter("QuestionType", typeof(string));
    
            var categoryParameter = category != null ?
                new ObjectParameter("Category", category) :
                new ObjectParameter("Category", typeof(string));
    
            var questionParameter = question != null ?
                new ObjectParameter("Question", question) :
                new ObjectParameter("Question", typeof(string));
    
            var optionAParameter = optionA != null ?
                new ObjectParameter("OptionA", optionA) :
                new ObjectParameter("OptionA", typeof(string));
    
            var optionBParameter = optionB != null ?
                new ObjectParameter("OptionB", optionB) :
                new ObjectParameter("OptionB", typeof(string));
    
            var optionCParameter = optionC != null ?
                new ObjectParameter("OptionC", optionC) :
                new ObjectParameter("OptionC", typeof(string));
    
            var optionDParameter = optionD != null ?
                new ObjectParameter("OptionD", optionD) :
                new ObjectParameter("OptionD", typeof(string));
    
            var answerParameter = answer != null ?
                new ObjectParameter("Answer", answer) :
                new ObjectParameter("Answer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addQuestion", questionTypeParameter, categoryParameter, questionParameter, optionAParameter, optionBParameter, optionCParameter, optionDParameter, answerParameter);
        }
    
        public virtual int addQuiz(string quizName, Nullable<int> totalQuestions, Nullable<int> timeAllocated, Nullable<int> passingScore, string subjects, Nullable<int> catID)
        {
            var quizNameParameter = quizName != null ?
                new ObjectParameter("QuizName", quizName) :
                new ObjectParameter("QuizName", typeof(string));
    
            var totalQuestionsParameter = totalQuestions.HasValue ?
                new ObjectParameter("TotalQuestions", totalQuestions) :
                new ObjectParameter("TotalQuestions", typeof(int));
    
            var timeAllocatedParameter = timeAllocated.HasValue ?
                new ObjectParameter("TimeAllocated", timeAllocated) :
                new ObjectParameter("TimeAllocated", typeof(int));
    
            var passingScoreParameter = passingScore.HasValue ?
                new ObjectParameter("PassingScore", passingScore) :
                new ObjectParameter("PassingScore", typeof(int));
    
            var subjectsParameter = subjects != null ?
                new ObjectParameter("Subjects", subjects) :
                new ObjectParameter("Subjects", typeof(string));
    
            var catIDParameter = catID.HasValue ?
                new ObjectParameter("CatID", catID) :
                new ObjectParameter("CatID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addQuiz", quizNameParameter, totalQuestionsParameter, timeAllocatedParameter, passingScoreParameter, subjectsParameter, catIDParameter);
        }
    
        public virtual int addSubject(string subjectName, string category, Nullable<int> activeF)
        {
            var subjectNameParameter = subjectName != null ?
                new ObjectParameter("SubjectName", subjectName) :
                new ObjectParameter("SubjectName", typeof(string));
    
            var categoryParameter = category != null ?
                new ObjectParameter("Category", category) :
                new ObjectParameter("Category", typeof(string));
    
            var activeFParameter = activeF.HasValue ?
                new ObjectParameter("ActiveF", activeF) :
                new ObjectParameter("ActiveF", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addSubject", subjectNameParameter, categoryParameter, activeFParameter);
        }
    
        public virtual int addUser(string userName, string firstName, string lastName, string password, string email, string phoneNumber, string secretQuestion, string secretAnswer, Nullable<int> role)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("PhoneNumber", phoneNumber) :
                new ObjectParameter("PhoneNumber", typeof(string));
    
            var secretQuestionParameter = secretQuestion != null ?
                new ObjectParameter("SecretQuestion", secretQuestion) :
                new ObjectParameter("SecretQuestion", typeof(string));
    
            var secretAnswerParameter = secretAnswer != null ?
                new ObjectParameter("SecretAnswer", secretAnswer) :
                new ObjectParameter("SecretAnswer", typeof(string));
    
            var roleParameter = role.HasValue ?
                new ObjectParameter("Role", role) :
                new ObjectParameter("Role", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addUser", userNameParameter, firstNameParameter, lastNameParameter, passwordParameter, emailParameter, phoneNumberParameter, secretQuestionParameter, secretAnswerParameter, roleParameter);
        }
    
        public virtual int assignQuizToAgent(Nullable<int> quizId, Nullable<int> teacherId, string expireDate, string agents)
        {
            var quizIdParameter = quizId.HasValue ?
                new ObjectParameter("QuizId", quizId) :
                new ObjectParameter("QuizId", typeof(int));
    
            var teacherIdParameter = teacherId.HasValue ?
                new ObjectParameter("TeacherId", teacherId) :
                new ObjectParameter("TeacherId", typeof(int));
    
            var expireDateParameter = expireDate != null ?
                new ObjectParameter("ExpireDate", expireDate) :
                new ObjectParameter("ExpireDate", typeof(string));
    
            var agentsParameter = agents != null ?
                new ObjectParameter("Agents", agents) :
                new ObjectParameter("Agents", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("assignQuizToAgent", quizIdParameter, teacherIdParameter, expireDateParameter, agentsParameter);
        }
    
        public virtual ObjectResult<string> convertToTable(string inputValue)
        {
            var inputValueParameter = inputValue != null ?
                new ObjectParameter("InputValue", inputValue) :
                new ObjectParameter("InputValue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("convertToTable", inputValueParameter);
        }
    
        public virtual int deleteQuestion(Nullable<int> qId)
        {
            var qIdParameter = qId.HasValue ?
                new ObjectParameter("QId", qId) :
                new ObjectParameter("QId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteQuestion", qIdParameter);
        }
    
        public virtual int deleteQuiz(Nullable<int> quizId)
        {
            var quizIdParameter = quizId.HasValue ?
                new ObjectParameter("QuizId", quizId) :
                new ObjectParameter("QuizId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteQuiz", quizIdParameter);
        }
    
        public virtual int deleteSubject(Nullable<int> sId)
        {
            var sIdParameter = sId.HasValue ?
                new ObjectParameter("SId", sId) :
                new ObjectParameter("SId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteSubject", sIdParameter);
        }
    
        public virtual int deleteUser(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteUser", userIdParameter);
        }
    
        public virtual int editUser(Nullable<int> userId, string userName, string firstName, string lastName, string password, string email, string phoneNumber, string secretQuestion, string secretAnswer, string role)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("PhoneNumber", phoneNumber) :
                new ObjectParameter("PhoneNumber", typeof(string));
    
            var secretQuestionParameter = secretQuestion != null ?
                new ObjectParameter("SecretQuestion", secretQuestion) :
                new ObjectParameter("SecretQuestion", typeof(string));
    
            var secretAnswerParameter = secretAnswer != null ?
                new ObjectParameter("SecretAnswer", secretAnswer) :
                new ObjectParameter("SecretAnswer", typeof(string));
    
            var roleParameter = role != null ?
                new ObjectParameter("Role", role) :
                new ObjectParameter("Role", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("editUser", userIdParameter, userNameParameter, firstNameParameter, lastNameParameter, passwordParameter, emailParameter, phoneNumberParameter, secretQuestionParameter, secretAnswerParameter, roleParameter);
        }
    
        public virtual ObjectResult<getAgentGridData_Result> getAgentGridData(Nullable<int> uid)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAgentGridData_Result>("getAgentGridData", uidParameter);
        }
    
        public virtual ObjectResult<getAgents_Result> getAgents()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAgents_Result>("getAgents");
        }
    
        public virtual ObjectResult<getQuestionList_Result> getQuestionList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getQuestionList_Result>("getQuestionList");
        }
    
        public virtual ObjectResult<GetQuizData_Agent_Result> GetQuizData_Agent(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetQuizData_Agent_Result>("GetQuizData_Agent", userIdParameter);
        }
    
        public virtual ObjectResult<getQuizList_Result> getQuizList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getQuizList_Result>("getQuizList");
        }
    
        public virtual ObjectResult<GetQuizQuestions_Result> GetQuizQuestions(Nullable<int> userId, Nullable<int> quizID)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var quizIDParameter = quizID.HasValue ?
                new ObjectParameter("QuizID", quizID) :
                new ObjectParameter("QuizID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetQuizQuestions_Result>("GetQuizQuestions", userIdParameter, quizIDParameter);
        }
    
        public virtual ObjectResult<getRoles_Result> getRoles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getRoles_Result>("getRoles");
        }
    
        public virtual ObjectResult<getSecretQuestions_Result> getSecretQuestions()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getSecretQuestions_Result>("getSecretQuestions");
        }
    
        public virtual ObjectResult<getSubjects_Result> getSubjects(Nullable<int> catid)
        {
            var catidParameter = catid.HasValue ?
                new ObjectParameter("catid", catid) :
                new ObjectParameter("catid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getSubjects_Result>("getSubjects", catidParameter);
        }
    
        public virtual ObjectResult<getSubjectsList_Result> getSubjectsList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getSubjectsList_Result>("getSubjectsList");
        }
    
        public virtual ObjectResult<getTestCategories_Result> getTestCategories()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getTestCategories_Result>("getTestCategories");
        }
    
        public virtual ObjectResult<getUserDetails_Result> getUserDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getUserDetails_Result>("getUserDetails");
        }
    }
}
